SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME,LAST_NAME FROM EMPLOYEES;

select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;

SELECT JOB_ID, JOB_TITLE FROM JOBS;

SELECT * FROM COUNTRIES;

SELECT * FROM REGIONS;




