SELECT * FROM EMPLOYEES;

SELECT COUNT(FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(REGION_ID) FROM REGIONS;



-- COUNT STATEMENT IS NOT INCLUDING NULL VALUES
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;

