SELECT FIRST_NAME FROM EMPLOYEES;

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;

SELECT FIRST_NAME,PHONE_NUMBER,SALARY FROM EMPLOYEES;

SELECT DISTINCT JOB_ID FROM EMPLOYEES;


