select JOB_ID, SALARY from EMPLOYEES;

select avg(SALARY) from EMPLOYEES
where JOB_ID = 'IT_PROG';

SELECT JOB_ID , AVG(SALARY) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, MAX(HIRE_DATE) FROM EMPLOYEES
GROUP BY JOB_ID;

-- get me maximum salary of each department_id
select department_id , max(salary)from employees group by department_id;


-- get me how many employees in each job_id
SELECT JOB_ID, COUNT(JOB_ID) FROM EMPLOYEES
GROUP BY JOB_ID;

-- get me salary information( min, max, sum, avg) of each job_id
SELECT JOB_ID, MIN(SALARY), MAX(SALARY), SUM(SALARY), AVG(SALARY) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM EMPLOYEES
GROUP BY JOB_ID
HAVING SUM(SALARY) > 20000;

SELECT JOB_ID, SUM(SALARY) FROM EMPLOYEES
WHERE SALARY > 20000
GROUP BY JOB_ID;

-- Get me department_id who has more than 10 employee
SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 10;

SELECT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DEPARTMENT_ID, COUNT(DEPARTMENT_ID) FROM EMPLOYEES
WHERE DEPARTMENT_ID > 10
GROUP BY DEPARTMENT_ID;

-- get me which job_id has average commission_pct over 20% = 0.2
SELECT JOB_ID, AVG(COMMISSION_PCT) FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(COMMISSION_PCT) > 0.2;

-- get me each manager_id max salary and find out those more than 10000
SELECT MANAGER_ID, MAX(SALARY) FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MAX(SALARY) > 10000
ORDER BY MANAGER_ID ASC ;




