SELECT SALARY FROM EMPLOYEES;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY = 24000;

SELECT FIRST_NAME FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT FIRST_NAME, SALARY  FROM EMPLOYEES
WHERE ROWNUM < 11;

SELECT FIRST_NAME,SALARY FROM (SELECT FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC )
WHERE ROWNUM < 11;


-- get me those departments whose employees more than department 80
SELECT COUNT(DEPARTMENT_ID) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;

SELECT DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_ID) > (SELECT COUNT(DEPARTMENT_ID) FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80);


-- get me those employees who is older than any IT programmer in the company
SELECT MIN(HIRE_DATE) FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';

SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE < (SELECT MIN(HIRE_DATE) FROM EMPLOYEES
                   WHERE JOB_ID = 'IT_PROG');


